doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Accueil:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Accueil/Entity'
                prefix: 'App\Accueil\Entity'
                alias: Accueil
            Blocoperatoire:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blocoperatoire/Entity'
                prefix: 'App\Blocoperatoire\Entity'
                alias: Blocoperatoire
            Consultation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Consultation/Entity'
                prefix: 'App\Consultation\Entity'
                alias: Consultation
            Dispensaire:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Dispensaire/Entity'
                prefix: 'App\Dispensaire\Entity'
                alias: Dispensaire
            Economat:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Economat/Entity'
                prefix: 'App\Economat\Entity'
                alias: Economat
            Facturation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Facturation/Entity'
                prefix: 'App\Facturation\Entity'
                alias: Facturation
            Pharmaciedetails:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Pharmaciedetails/Entity'
                prefix: 'App\Pharmaciedetails\Entity'
                alias: Pharmaciedetails
            Pharmaciegros:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Pharmaciegros/Entity'
                prefix: 'App\Pharmaciegros\Entity'
                alias: Pharmaciegros
            Prisedesparametres:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Prisedesparametres/Entity'
                prefix: 'App\Prisedesparametres\Entity'
                alias: Prisedesparametres
            Servicemedical:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Servicemedical/Entity'
                prefix: 'App\Servicemedical\Entity'
                alias: Servicemedical
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Entity'
                prefix: 'App\Shared\Entity'
                alias: Shared
            Urgence:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Urgence/Entity'
                prefix: 'App\Urgence\Entity'
                alias: Urgence


        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
